version: "3.9"
services:
  db:
    image: postgres:15
    container_name: adsdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer:4
    restart: unless-stopped
    ports:
      - "8080:8080"
volumes:
  pgdata: